"""Sector packs - the plug-in / plug-out layer.

WHY THIS EXISTS
---------------
The engine must stay sector-agnostic: corroboration, scoring and the output
checks know nothing about payments or telecoms, and they must not, or every new
vertical becomes a branch inside the machine. But a payments processor and a grid
operator need genuinely different things - different regulators, different
evidence, different board language, different dates.

A **pack** is how that difference is supplied from outside the engine. It is
declarative content, not code: the controls a sector is audited against, the
evidence an auditor will ask for, the milestone calendar, the framing a board
memo opens with, and the questions an insurer now asks. Enabling a pack changes
what the product *says*; it never changes how the engine *computes*.

    engine core      agnostic, never edited per sector
      + sector pack  regulators, controls, evidence, dates, language
      + sensor pack  connectors (engine/plugins.py)
      = a product that fits one kind of organisation

Packs can be enabled and disabled at runtime. That is the point: agnosticism is
demonstrable rather than asserted, because a sector can be unplugged in front of
someone and the same estate is then judged by different rules.

CONTENT PROVENANCE
------------------
Every pack cites where its content came from - a published standard, a
regulator's document, a vendor's own release notes. Nothing here is inferred
from customer data and nothing is generated by a model. A control mapping that
cannot name its source is a liability in the one conversation it exists for.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ComplianceControl:
    """A control this sector is audited against, and what answers it."""

    id: str
    framework: str
    requirement: str
    #: Which engine output constitutes evidence. This is the whole value: an
    #: auditor's question mapped to something the product already produces.
    answered_by: str


@dataclass(frozen=True)
class Milestone:
    """A dated obligation. Sourced, because a wrong date is worse than none."""

    year: int
    label: str
    source: str
    binding: bool = False


@dataclass(frozen=True)
class SectorPack:
    """Declarative content that specialises the agnostic engine."""

    id: str
    name: str
    version: str
    sector: str
    summary: str
    controls: list[ComplianceControl] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    milestones: list[Milestone] = field(default_factory=list)
    board_framing: str = ""
    insurance_questions: list[str] = field(default_factory=list)
    sources: list[str] = field(default_factory=list)

    def to_dict(self, enabled: bool) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "version": self.version,
            "sector": self.sector,
            "summary": self.summary,
            "enabled": enabled,
            "controls": [
                {
                    "id": c.id, "framework": c.framework,
                    "requirement": c.requirement, "answered_by": c.answered_by,
                }
                for c in self.controls
            ],
            "evidence": list(self.evidence),
            "milestones": [
                {"year": m.year, "label": m.label, "source": m.source,
                 "binding": m.binding}
                for m in sorted(self.milestones, key=lambda m: m.year)
            ],
            "board_framing": self.board_framing,
            "insurance_questions": list(self.insurance_questions),
            "sources": list(self.sources),
            "counts": {
                "controls": len(self.controls),
                "milestones": len(self.milestones),
                "binding_milestones": sum(1 for m in self.milestones if m.binding),
            },
        }


PACKS: dict[str, SectorPack] = {}


def _register(pack: SectorPack) -> SectorPack:
    PACKS[pack.id] = pack
    return pack


_register(SectorPack(
    id="pack.payments",
    name="Payments & card acquiring",
    version="1.0.0",
    sector="payments",
    summary=(
        "PCI DSS already requires a documented key and certificate inventory "
        "with named custodians. This pack maps that obligation onto engine "
        "output so the inventory is continuously true rather than true once."
    ),
    controls=[
        ComplianceControl(
            "PCI-DSS-3.6", "PCI DSS 4.0.1",
            "Document and maintain an inventory of all cryptographic keys, their "
            "purpose, strength and custodian.",
            "Asset inventory plus the ownership gap report: the engine reports "
            "which keys have no named owner rather than leaving the row blank.",
        ),
        ComplianceControl(
            "PCI-DSS-12.3.3", "PCI DSS 4.0.1",
            "Maintain a documented inventory of cryptographic suites and protocols "
            "in use, reviewed at least annually, with a documented plan to respond "
            "to anticipated changes in cryptographic vulnerabilities. Best practice "
            "until 31 March 2025; assessable since.",
            "The CycloneDX CBOM export, regenerated on every scan and validated "
            "against 16 structural rules, plus GET /api/evidence/pci-1233 — a "
            "PCI 12.3.3-shaped workpaper draft (not a QSA attestation).",
        ),
        ComplianceControl(
            "PCI-PIN-A", "PCI PIN Security",
            "PIN encryption keys must be managed within an approved HSM boundary.",
            "The HSM connector inventories key objects over PKCS#11 without ever "
            "reading key material - the HSM refuses, which is itself the evidence.",
        ),
        ComplianceControl(
            "RBI-QSAFE-1", "RBI Q-SAFE (India)",
            "Sector-wide diagnostic audit using a Cryptography Bill of Materials.",
            "The same CBOM, framed in the shape the regulator asked for.",
        ),
    ],
    evidence=[
        "CycloneDX 1.6 CBOM, schema-valid",
        "Key inventory with custodian, and ownership gaps stated rather than blank",
        "HSM mechanism list showing which keys are vendor-blocked for PQC",
        "Engine trace: the derivation behind every ranked item",
    ],
    milestones=[
        Milestone(2026, "RBI Q-SAFE committee reports (~Nov)", "RBI, May 2026"),
        Milestone(2027, "New NSS acquisitions CNSA 2.0 by default", "CNSA 2.0", binding=True),
        Milestone(2030, "Quantum-vulnerable algorithms deprecated", "NIST IR 8547 (draft)"),
        Milestone(2035, "Quantum-vulnerable algorithms disallowed", "NIST IR 8547 (draft)"),
    ],
    board_framing=(
        "Cryptographic inventory is already a PCI requirement and is becoming an "
        "RBI one. The exposure is not hypothetical: an expired certificate on a "
        "settlement path is an outage this quarter, and the same inventory "
        "prevents that and the 2030 deadline with one piece of work."
    ),
    insurance_questions=[
        "Can you produce a current inventory of cryptographic keys and certificates?",
        "Do you have a documented post-quantum transition plan with dates?",
        "Which cryptographic assets cannot be migrated on your vendors' roadmaps?",
    ],
    sources=[
        "PCI DSS 4.0.1 requirements 3.6 and 12.3.3 (12.3.3 assessable since 31 March 2025)",
        "PCI PIN Security Requirements",
        "RBI Q-SAFE committee terms of reference, May 2026",
        "NIST IR 8547",
    ],
))

_register(SectorPack(
    id="pack.government",
    name="Government & public sector",
    version="1.0.0",
    sector="government",
    summary=(
        "The only sector where the dates are already law. This pack carries the "
        "binding federal calendar and the procurement rules that push the same "
        "obligation onto suppliers."
    ),
    controls=[
        ComplianceControl(
            "EO-14412-INV", "US EO 14412 (Jun 2026)",
            "Maintain an inventory of high-value assets using quantum-vulnerable "
            "cryptography and submit a migration plan.",
            "The prioritised backlog with its Mosca category and statutory slack "
            "per asset, plus the assets flagged as insufficiently evidenced.",
        ),
        ComplianceControl(
            "CNSA-2.0-ACQ", "CNSA 2.0",
            "New national security system acquisitions must be quantum-resistant.",
            "Verdict and PQC-replacement mapping per asset class.",
        ),
        ComplianceControl(
            "IR-8547-DEPR", "NIST IR 8547",
            "Plan for deprecation of quantum-vulnerable algorithms by 2030.",
            "Migration roadmap against the deprecation calendar.",
        ),
    ],
    evidence=[
        "Migration plan with dated milestones per high-value asset",
        "CBOM covering in-scope systems",
        "Pipeline check report and run digest showing how the ranking was produced",
        "Supplier attestation status for FAR-covered contractors",
    ],
    milestones=[
        Milestone(2027, "New NSS acquisitions quantum-resistant", "CNSA 2.0", binding=True),
        Milestone(2030, "Legacy equipment transition complete", "EO 14412", binding=True),
        Milestone(2031, "CNSA 2.0 mandatory across covered categories", "CNSA 2.0", binding=True),
        Milestone(2033, "Exclusive CNSA 2.0 use for OS, applications, cloud", "CNSA 2.0", binding=True),
        Milestone(2035, "Full quantum resistance across NSS", "NSM-10", binding=True),
    ],
    board_framing=(
        "These dates are statutory. The auditor will not ask whether we intend "
        "to migrate; they will ask whether the inventory survives scrutiny, "
        "including the parts we could not measure."
    ),
    insurance_questions=[
        "Is a PQC migration plan filed and current?",
        "Are contractor flow-down requirements tracked per supplier?",
    ],
    sources=[
        "US Executive Order 14412, June 2026",
        "CNSA 2.0 timelines",
        "NIST IR 8547",
    ],
))

_register(SectorPack(
    id="pack.telecom",
    name="Telecommunications",
    version="1.0.0",
    sector="telecom",
    summary=(
        "GSMA has published a PQC standard specific to telecom use cases, and it "
        "names cryptographic inventory as the first workstream."
    ),
    controls=[
        ComplianceControl(
            "GSMA-PQ03-INV", "GSMA PQ.03",
            "Establish a cryptographic inventory across network functions before "
            "planning migration.",
            "Asset inventory with per-sensor coverage, and an explicit statement "
            "of the network segments no sensor reached.",
        ),
        ComplianceControl(
            "GSMA-PQ03-PKI", "GSMA PQ.03",
            "Assess PKI implications of migration, including interconnect trust.",
            "Dependency graph with blast radius, plus the cross-organisation "
            "readiness gate for interconnect partners.",
        ),
        ComplianceControl(
            "GSMA-PQ03-DATA", "GSMA PQ.03",
            "Identify sensitive data with long confidentiality requirements.",
            "Harvest-now exposure by confidentiality horizon, from the HNDL axis.",
        ),
    ],
    evidence=[
        "Inventory per network function with coverage gaps named",
        "Interconnect partner readiness status",
        "Hardware lifecycle exposure: assets that cannot migrate before end-of-life",
    ],
    milestones=[
        Milestone(2026, "GSMA PQ.03 v2.0 guidance in force", "GSMA"),
        Milestone(2030, "Algorithms deprecated", "NIST IR 8547 (draft)"),
        Milestone(2035, "Algorithms disallowed", "NIST IR 8547 (draft)"),
    ],
    board_framing=(
        "The standard for our sector already exists. The gap is that much of the "
        "estate runs on hardware commissioned before it was written and cannot "
        "be migrated within its service life."
    ),
    insurance_questions=[
        "Can you evidence a cryptographic inventory across core network functions?",
        "What proportion of the estate cannot be migrated before end-of-life?",
    ],
    sources=[
        "GSMA PQ.03 - PQC Guidelines for Telecom Use Cases v2.0",
        "GSMA Post Quantum Telco Network Task Force",
    ],
))

_register(SectorPack(
    id="pack.erp",
    name="ERP landscape",
    version="1.0.0",
    sector="erp",
    summary=(
        "The vendor already shipped quantum-safe cryptography. What no ERP "
        "customer has is a per-system record of which systems can actually use "
        "it, and what breaks when trust between them changes."
    ),
    controls=[
        ComplianceControl(
            "ERP-LIB-VER", "Vendor baseline",
            "Record the cryptographic library version deployed on each system.",
            "Configuration sensor output per system - a capability inventory, not "
            "a risk score. A system below the required version cannot do hybrid "
            "PQC regardless of what the migration plan says.",
        ),
        ComplianceControl(
            "ERP-TRUST-MAP", "Operational",
            "Map system-to-system trust so rotation does not halt interfaces.",
            "Dependency graph plus migration preview: what breaks if this trust "
            "anchor rotates, and which counterparties must move first.",
        ),
        ComplianceControl(
            "SOX-ITGC", "SOX ITGC",
            "Controls over the integrity of financially relevant systems.",
            "Evidence pack with the engine trace behind every conclusion.",
        ),
    ],
    evidence=[
        "Cryptographic library version per system across the landscape",
        "System-to-system trust map with rotation blast radius",
        "Migration preview for each planned rotation",
    ],
    milestones=[
        Milestone(2026, "Hybrid quantum-safe TLS in current library releases", "Vendor release notes"),
        Milestone(2027, "New NSS acquisitions must support CNSA 2.0", "CNSA 2.0", binding=True),
        Milestone(2030, "Algorithms deprecated", "NIST IR 8547 (draft)"),
    ],
    board_framing=(
        "Our vendor has solved the algorithm. We have not solved the landscape: "
        "we cannot say which systems are capable, and rotating one trust "
        "relationship can stop interfaces across the estate."
    ),
    insurance_questions=[
        "Can you enumerate cryptographic capability per production system?",
    ],
    sources=[
        "SAP CommonCryptoLib 8.6 release notes (hybrid X25519MLKEM768, FIPS 140-3 mode)",
        "SAP HANA CommonCryptoLib documentation",
    ],
))

_register(SectorPack(
    id="pack.energy",
    name="Energy & utilities",
    version="1.0.0",
    sector="energy",
    summary=(
        "No PQC mandate exists yet for this sector - the regulator flagged "
        "quantum as an emerging risk and stopped short. That gap is the reason "
        "to start now, because the inventory outlasts the wait."
    ),
    controls=[
        ComplianceControl(
            "NERC-CIP-EMERG", "NERC CIP Roadmap 2026",
            "Quantum computing identified as an Emerging Security Risk; no CIP "
            "requirement yet.",
            "Inventory and lifecycle exposure report, positioned ahead of the "
            "requirement rather than in response to it.",
        ),
        ComplianceControl(
            "IEC-62443-SR", "IEC 62443",
            "Security requirements for industrial automation and control systems.",
            "Device identity and firmware signing inventory with change "
            "difficulty per asset class.",
        ),
    ],
    evidence=[
        "Field device cryptographic inventory with commissioning dates",
        "Assets whose service life exceeds the algorithm deprecation date",
        "Change difficulty banding: what is a config change, what is a truck roll",
    ],
    milestones=[
        Milestone(2026, "NERC CIP roadmap lists quantum as emerging risk", "NERC, Jan 2026"),
        Milestone(2030, "Algorithms deprecated", "NIST IR 8547 (draft)"),
        Milestone(2035, "Algorithms disallowed", "NIST IR 8547 (draft)"),
    ],
    board_framing=(
        "There is no mandate yet. There is also a fleet commissioned for "
        "twenty-five years, which means assets installed this year will still be "
        "running after the algorithms they use are disallowed."
    ),
    insurance_questions=[
        "What share of operational technology uses quantum-vulnerable cryptography?",
        "What is the replacement horizon for those assets?",
    ],
    sources=["NERC CIP Roadmap, January 2026", "IEC 62443", "NIST IR 8547"],
))

_register(SectorPack(
    id="pack.healthcare",
    name="Healthcare & life sciences",
    version="1.0.0",
    sector="healthcare",
    summary=(
        "Retention measured in decades makes this the worst harvest-now exposure "
        "of any sector: data encrypted today must stay secret for longer than "
        "the algorithm protecting it will last."
    ),
    controls=[
        ComplianceControl(
            "HIPAA-164.312", "HIPAA Security Rule",
            "Mechanisms to encrypt electronic protected health information.",
            "Confidentiality-horizon analysis: which records outlive their key.",
        ),
        ComplianceControl(
            "DPDP-SEC", "DPDP Act 2023 (India)",
            "Reasonable security safeguards for personal data.",
            "Sensitivity-weighted inventory with retention horizon per asset.",
        ),
        ComplianceControl(
            "MD-CYBER", "Medical device cybersecurity",
            "Evidence cryptographic controls over device service life.",
            "Device identity and firmware signing inventory with fleet exposure.",
        ),
    ],
    evidence=[
        "Records whose retention period exceeds their key's safe horizon",
        "Connected medical device cryptographic inventory",
        "Re-encryption plan for archives, distinct from endpoint migration",
    ],
    milestones=[
        Milestone(2030, "Algorithms deprecated", "NIST IR 8547 (draft)"),
        Milestone(2035, "Algorithms disallowed", "NIST IR 8547 (draft)"),
    ],
    board_framing=(
        "A record we must keep for a patient's lifetime, encrypted with a key "
        "that has an eight-year horizon, is a breach with a delayed disclosure "
        "date. Migrating the endpoint does not fix the archive."
    ),
    insurance_questions=[
        "Do you hold long-retention data protected by quantum-vulnerable cryptography?",
        "Is there a re-encryption plan for archives, separate from transport migration?",
    ],
    sources=["HIPAA Security Rule 164.312", "DPDP Act 2023", "NIST IR 8547"],
))

_register(SectorPack(
    id="pack.baseline",
    name="Baseline (sector-neutral)",
    version="1.0.0",
    sector="*",
    summary=(
        "Applies when no sector pack does. Carries only what binds everyone, so "
        "the product is useful before a vertical is chosen - and so the engine "
        "is visibly agnostic with every sector pack unplugged."
    ),
    controls=[
        ComplianceControl(
            "ISO-27001-A.10", "ISO/IEC 27001:2022",
            "Policy on the use of cryptographic controls, including key management.",
            "Policy inputs per asset class, each carrying a written rationale.",
        ),
        ComplianceControl(
            "SOC2-CC6.1", "SOC 2",
            "Logical access controls including encryption in transit and at rest.",
            "Verdict and coverage report per asset.",
        ),
    ],
    evidence=[
        "CycloneDX CBOM",
        "Coverage statement naming what no sensor reached",
    ],
    milestones=[
        Milestone(2030, "Algorithms deprecated", "NIST IR 8547 (draft)"),
        Milestone(2035, "Algorithms disallowed", "NIST IR 8547 (draft)"),
    ],
    board_framing=(
        "Two dates bind everyone regardless of sector: deprecation in 2030 and "
        "disallowance in 2035. Everything else is local detail."
    ),
    insurance_questions=[
        "Can you produce a current cryptographic inventory on request?",
    ],
    sources=["ISO/IEC 27001:2022", "SOC 2 Trust Services Criteria", "NIST IR 8547"],
))


# --------------------------------------------------------------------------
# Registry - the plug in / plug out surface
# --------------------------------------------------------------------------


class PackRegistry:
    """Which packs exist, and which are currently plugged in."""

    def __init__(self):
        # Baseline is always on. With every sector pack unplugged the product
        # must still be correct and useful, which is what agnostic actually
        # means - not "has no opinions" but "degrades to the universal ones".
        self._enabled: set[str] = {"pack.baseline"}

    def enable(self, pack_id: str) -> bool:
        if pack_id not in PACKS:
            return False
        self._enabled.add(pack_id)
        return True

    def disable(self, pack_id: str) -> bool:
        # Unplugging the floor is not a supported state: it would leave the
        # product with nothing to say rather than with less to say.
        if pack_id == "pack.baseline":
            return False
        self._enabled.discard(pack_id)
        return True

    def is_enabled(self, pack_id: str) -> bool:
        return pack_id in self._enabled

    def for_sector(self, sector: str) -> list[SectorPack]:
        """Enabled packs applying to a sector, most specific first."""
        matched = [
            p for p in PACKS.values()
            if p.sector == sector and self.is_enabled(p.id)
        ]
        baseline = PACKS["pack.baseline"]
        if self.is_enabled(baseline.id) and baseline not in matched:
            matched.append(baseline)
        return matched

    def describe(self) -> list[dict]:
        return [p.to_dict(self.is_enabled(p.id)) for p in PACKS.values()]

    def resolved(self, sector: str) -> dict:
        """Everything the product should say for this sector, merged.

        Sector packs take precedence and baseline fills the gaps, so unplugging
        a sector pack degrades the output to something still correct rather than
        to something empty. Duplicates are collapsed on identity, not on text,
        because two frameworks can word the same obligation differently and both
        need to appear.
        """
        packs = self.for_sector(sector)
        controls: list[dict] = []
        evidence: list[str] = []
        milestones: list[dict] = []
        questions: list[str] = []
        sources: list[str] = []
        framing = ""

        seen_controls: set[str] = set()
        seen_milestones: set[tuple] = set()

        for pack in packs:
            data = pack.to_dict(True)
            if not framing and data["board_framing"]:
                framing = data["board_framing"]
            for control in data["controls"]:
                if control["id"] not in seen_controls:
                    seen_controls.add(control["id"])
                    controls.append(control)
            for milestone in data["milestones"]:
                key = (milestone["year"], milestone["label"])
                if key not in seen_milestones:
                    seen_milestones.add(key)
                    milestones.append(milestone)
            for item in data["evidence"]:
                if item not in evidence:
                    evidence.append(item)
            for question in data["insurance_questions"]:
                if question not in questions:
                    questions.append(question)
            for source in data["sources"]:
                if source not in sources:
                    sources.append(source)

        milestones.sort(key=lambda m: m["year"])

        return {
            "sector": sector,
            "packs_applied": [p.id for p in packs],
            "board_framing": framing,
            "controls": controls,
            "evidence": evidence,
            "milestones": milestones,
            "insurance_questions": questions,
            "sources": sources,
            "note": (
                "Content supplied by sector packs. The engine's computation is "
                "identical for every sector; only what is said about the result "
                "changes."
            ),
        }


REGISTRY = PackRegistry()


def enable_all_sector_packs() -> None:
    """Default posture: every pack plugged in, so any sector is selectable."""
    for pack_id in PACKS:
        REGISTRY.enable(pack_id)


enable_all_sector_packs()


# --------------------------------------------------------------------------
# QIRS profile resolution data
#
# Adapters MUST set asset_class on every finding. These tables exist only for
# legacy assets that predate that requirement (source_type=config/source with
# no class). The branch lives in pack DATA, not in qirs if-statements.
# --------------------------------------------------------------------------

# Tag / custody / usage hint → profile key. Checked before source_type.
USAGE_OR_HINT_PROFILES: dict[str, str] = {
    "config": "config",
    "source": "source",
    "server_config": "config",
    "api_call": "source",
    "static_source": "source",
    "cipher_config": "config",
}

# Last-resort map for assets that only carried source_type. Do not add new
# entries here — set asset_class in the adapter instead.
LEGACY_SOURCE_TYPE_PROFILES: dict[str, str] = {
    "config": "config",
    "source": "source",
}


def resolve_qirs_profile_key(asset) -> str | None:
    """Legacy / hint path for QIRS profile selection.

    Returns a candidate profile key, or None when nothing matches. The caller
    (engine.qirs.resolve_profile) validates the key against PROFILES.

    Adapters MUST set asset_class. This helper exists for assets that only
    carried source_type=config/source (or tag/custody hints) with no class.
    """
    details = getattr(asset, "raw_details", None) or {}
    explicit = details.get("qirs_profile")
    if isinstance(explicit, str) and explicit:
        return explicit

    # Custody dict or free-form tags may carry a profile hint.
    custody = details.get("custody")
    hint_candidates: list[str] = []
    if isinstance(custody, dict):
        for key in ("kind", "type", "profile", "hint"):
            value = custody.get(key)
            if isinstance(value, str) and value:
                hint_candidates.append(value)
    elif isinstance(custody, str) and custody:
        hint_candidates.append(custody)

    for tag in getattr(asset, "tags", None) or []:
        if isinstance(tag, str) and tag:
            hint_candidates.append(tag)

    usage = getattr(asset, "usage", None)
    if isinstance(usage, str) and usage and usage != "key_exchange":
        hint_candidates.append(usage)

    for hint in hint_candidates:
        mapped = USAGE_OR_HINT_PROFILES.get(hint) or USAGE_OR_HINT_PROFILES.get(hint.lower())
        if mapped:
            return mapped
        # A tag that is already a profile key name.
        if hint in USAGE_OR_HINT_PROFILES.values() or hint in LEGACY_SOURCE_TYPE_PROFILES.values():
            return hint

    discovered = str(details.get("discovered_by") or "")
    discovered_l = discovered.lower()
    if "source" in discovered_l and "config" not in discovered_l:
        return "source"
    if "config" in discovered_l:
        return "config"

    # Last resort: legacy source_type table. Adapters must set asset_class.
    source_type = getattr(asset, "source_type", None) or ""
    return LEGACY_SOURCE_TYPE_PROFILES.get(source_type)
