"""Post-quantum era threats — the register that keeps working after migration.

WHY THIS EXISTS
---------------
Every product in this category treats post-quantum cryptography as a destination:
score the estate, rank the backlog, migrate to ML-KEM, done. That is wrong in a
way that will become obvious to customers around 2029, and it is the reason this
module exists.

**Migrating to a post-quantum algorithm does not end cryptographic risk. It
changes which risks apply.** Four of them are already documented:

  1. The new algorithms have **implementation** vulnerabilities. ML-KEM and
     ML-DSA are mathematically sound but their physical implementations leak;
     side-channel and fault attacks against masked implementations are an active
     research area with published results on real devices.
  2. The new algorithms have had **far less cryptanalysis** than RSA or ECC.
     Module lattices are a structured variant chosen for performance, and that
     structure is exactly what a future attack would exploit.
  3. **Harvest-now-decrypt-later is retroactive.** Traffic captured before
     migration stays captured. Migrating the endpoint does not un-capture it.
  4. **The threat model itself moves.** Between May 2025 and March 2026 published
     estimates of the quantum resources needed to factor RSA-2048 fell from
     ~20 million qubits to under 1 million. An engine with a fixed survival curve
     was wrong the day that work appeared and had no way to notice.

A tool that stops at "migrated: yes" cannot express any of this. This register
is deliberately the part of the product that has no end state.

DESIGN NOTES
------------
Every entry is a stated, sourced position with an explicit `status`, not a
severity score. These are conditions of the world, not properties of one estate;
`assess` maps them onto an estate to say which apply *here*.

Nothing in this module is generated by a model, and none of it is a prediction.
Where the position depends on ongoing research, `review_by` says when the claim
should be re-checked, because a register that is never revisited becomes
misinformation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date


@dataclass(frozen=True)
class PQCThreat:
    """A risk that exists during or after a post-quantum migration."""

    key: str
    title: str
    #: active | emerging | monitored — how settled the evidence is.
    status: str
    summary: str
    #: What in an estate is exposed to it.
    applies_to: str
    #: What an operator can actually do.
    mitigation: str
    #: Where the claim comes from.
    evidence: str
    #: When this position should be re-checked.
    review_by: str


THREATS: list[PQCThreat] = [
    PQCThreat(
        key="pqc_side_channel",
        title="Side-channel and fault attacks on ML-KEM / ML-DSA implementations",
        status="active",
        summary=(
            "The standardised algorithms resist quantum cryptanalysis, but their "
            "implementations leak through timing, power and electromagnetic "
            "channels. Published attacks recover key material from masked "
            "implementations on physical devices, and a fault attack exists "
            "against the Arithmetic-to-Boolean conversion that masking itself "
            "introduces. Migrating to ML-KEM on unhardened hardware replaces a "
            "future risk with a present one."
        ),
        applies_to=(
            "Any asset already migrated to ML-KEM or ML-DSA, especially in "
            "hardware, embedded devices or HSMs where an attacker can obtain "
            "physical or co-located access."
        ),
        mitigation=(
            "Require certified, masked implementations from the vendor; treat "
            "'supports ML-KEM' and 'supports ML-KEM safely' as different "
            "questions in procurement. Prefer implementations with published "
            "side-channel evaluation."
        ),
        evidence=(
            "IACR ePrint 2025/276 (side-channel on masked ML-DSA); surveys of "
            "side-channel and fault attacks on ML-KEM; FPGA and microcontroller "
            "results, 2025-2026."
        ),
        review_by="2027-06-30",
    ),
    PQCThreat(
        key="lattice_cryptanalysis_immaturity",
        title="Structured-lattice assumptions have had far less scrutiny than RSA/ECC",
        status="monitored",
        summary=(
            "ML-KEM and ML-DSA rest on Module-LWE and Module-SIS. The module "
            "structure is chosen for performance and may admit attacks that "
            "unstructured lattices do not. No weakness is currently known — the "
            "issue is that these problems have been studied for roughly a decade "
            "against RSA's four. Two NIST-round candidates (SIKE, Rainbow) were "
            "broken during standardisation, which is the base rate to plan "
            "against."
        ),
        applies_to=(
            "Every asset migrated to a single post-quantum algorithm with no "
            "second option available."
        ),
        mitigation=(
            "Keep hybrid constructions rather than pure PQC where the cost is "
            "tolerable, and maintain the ability to switch algorithm families "
            "(lattice to hash-based) without re-architecting. Agility is the "
            "mitigation; there is no other one."
        ),
        evidence=(
            "NIST PQC project documentation; the SIKE and Rainbow breaks during "
            "standardisation; ongoing lattice cryptanalysis literature."
        ),
        review_by="2027-12-31",
    ),
    PQCThreat(
        key="retroactive_hndl",
        title="Traffic captured before migration remains exposed",
        status="active",
        summary=(
            "Harvest-now-decrypt-later is retroactive by construction. Migrating "
            "an endpoint protects traffic from that moment forward; it does "
            "nothing for ciphertext an adversary already holds. The exposure is "
            "therefore set by how long the data must stay secret and when "
            "migration actually happened — not by whether it happened."
        ),
        applies_to=(
            "Any long-retention data that transited a vulnerable channel before "
            "migration: archives, backups, records under statutory retention, "
            "and anything crossing a network an adversary can tap."
        ),
        mitigation=(
            "Re-encrypt archives under post-quantum protection rather than "
            "assuming migration covered them, and treat pre-migration retention "
            "windows as an accepted, documented loss where it does not."
        ),
        evidence=(
            "Established position of Western intelligence and national cyber "
            "authorities; CSA and vendor guidance, 2026."
        ),
        review_by="2027-06-30",
    ),
    PQCThreat(
        key="threat_model_drift",
        title="The quantum resource estimate is moving faster than migration plans",
        status="active",
        summary=(
            "Between May 2025 and March 2026 published estimates of the qubits "
            "needed to factor RSA-2048 fell from roughly 20 million to under one "
            "million, with some architectures suggesting far fewer. Nothing about "
            "any estate changed, but every deadline computed against the older "
            "estimate became less conservative. A risk model with a fixed "
            "survival curve cannot represent this; it simply becomes quietly "
            "wrong."
        ),
        applies_to=(
            "Every deadline, slack figure and migration schedule in this product "
            "and in every competing one."
        ),
        mitigation=(
            "Treat the survival curve as a versioned input, re-fit it when the "
            "literature moves, and re-run the schedule rather than the scan. "
            "Report the resulting movement as a change in the plan, not a "
            "correction to the data."
        ),
        evidence=(
            "Successive quantum resource-estimate papers, May 2025 - March 2026; "
            "Global Risk Institute Quantum Threat Timeline elicitations."
        ),
        review_by="2026-12-31",
    ),
    PQCThreat(
        key="hybrid_downgrade",
        title="Hybrid deployments can negotiate away their post-quantum half",
        status="emerging",
        summary=(
            "Hybrid key exchange (for example X25519MLKEM768) is the recommended "
            "transition posture, but a hybrid endpoint that still accepts a "
            "classical-only negotiation provides no post-quantum protection "
            "against an attacker who can influence negotiation, while reporting "
            "as 'PQC enabled' in every dashboard that checks capability rather "
            "than outcome."
        ),
        applies_to=(
            "Any endpoint advertised as post-quantum ready on the basis of "
            "supported algorithms rather than observed negotiations."
        ),
        mitigation=(
            "Verify the negotiated group on real handshakes, not the offered "
            "list, and alert when a hybrid-capable endpoint completes a "
            "classical-only exchange."
        ),
        evidence=(
            "TLS hybrid key exchange drafts and deployment measurement studies of "
            "post-quantum readiness on the public internet, 2026."
        ),
        review_by="2027-03-31",
    ),
    PQCThreat(
        key="agility_debt",
        title="Migrating without agility buys one move, not the ability to move",
        status="active",
        summary=(
            "An organisation that hardcodes ML-KEM in place of hardcoded RSA has "
            "spent a multi-year programme to arrive at the same structural "
            "position it started in. The next transition — driven by "
            "cryptanalysis, by a standards revision, or by a regulator — costs "
            "the same again. The measurable property is not which algorithm is "
            "deployed but how long it would take to change it."
        ),
        applies_to=(
            "Any asset whose algorithm is fixed in source or firmware rather than "
            "selected through configuration or a provider interface."
        ),
        mitigation=(
            "Track change-difficulty as a first-class property alongside risk, "
            "and treat a migration that does not reduce it as incomplete."
        ),
        evidence=(
            "NIST CSWP 39 crypto-agility guidance; CAMM maturity model "
            "(Hohm et al. 2023)."
        ),
        review_by="2027-12-31",
    ),
]

_BY_KEY = {t.key: t for t in THREATS}

STATUS_ORDER = {"active": 0, "emerging": 1, "monitored": 2}


def register() -> list[dict]:
    """The full register, most-settled evidence first."""
    return [
        {
            "key": t.key,
            "title": t.title,
            "status": t.status,
            "summary": t.summary,
            "applies_to": t.applies_to,
            "mitigation": t.mitigation,
            "evidence": t.evidence,
            "review_by": t.review_by,
            "review_overdue": t.review_by < date.today().isoformat(),
        }
        for t in sorted(THREATS, key=lambda t: (STATUS_ORDER.get(t.status, 9), t.title))
    ]


def assess(assets: list) -> dict:
    """Which post-quantum-era threats apply to this estate, and on what evidence.

    Deliberately conservative: an estate is only reported as exposed where a
    concrete, countable property of it triggers the threat. Nothing is asserted
    from the absence of data.
    """
    migrated = [a for a in assets if not getattr(a, "quantum_vulnerable", False)
                and getattr(a, "verdict", "") == "pqc"]
    hardware_bound = [
        a for a in assets
        if getattr(a, "asset_class", "") in {"payment_hsm", "firmware_signing", "device_identity"}
    ]
    long_retention = [a for a in assets if getattr(a, "x_c", 0) >= 8.0]
    hard_to_change = [
        a for a in assets
        if getattr(a, "agility_key", "") in {"hardware-bound", "vendor-blocked", "programme"}
    ]
    still_vulnerable = [a for a in assets if getattr(a, "quantum_vulnerable", False)]

    findings = []

    if migrated:
        findings.append({
            "threat": "pqc_side_channel",
            "exposed_count": len(migrated),
            "why": (
                f"{len(migrated)} asset(s) already use post-quantum algorithms. "
                "Their exposure is now an implementation property, not an "
                "algorithm property."
            ),
        })
        findings.append({
            "threat": "lattice_cryptanalysis_immaturity",
            "exposed_count": len(migrated),
            "why": (
                f"{len(migrated)} asset(s) depend on lattice assumptions that have "
                "had roughly a decade of scrutiny."
            ),
        })

    if hardware_bound:
        findings.append({
            "threat": "pqc_side_channel",
            "exposed_count": len(hardware_bound),
            "why": (
                f"{len(hardware_bound)} asset(s) are hardware-resident, which is "
                "where side-channel exposure is highest and remediation slowest."
            ),
        })

    if long_retention:
        findings.append({
            "threat": "retroactive_hndl",
            "exposed_count": len(long_retention),
            "why": (
                f"{len(long_retention)} asset(s) protect data with a "
                "confidentiality horizon of eight years or more. Anything already "
                "captured stays captured after migration."
            ),
        })

    if hard_to_change:
        findings.append({
            "threat": "agility_debt",
            "exposed_count": len(hard_to_change),
            "why": (
                f"{len(hard_to_change)} asset(s) cannot be changed by "
                "configuration, so the next algorithm transition costs as much as "
                "this one."
            ),
        })

    # Threat-model drift applies to every estate with a schedule, always.
    if assets:
        findings.append({
            "threat": "threat_model_drift",
            "exposed_count": len(still_vulnerable),
            "why": (
                f"{len(still_vulnerable)} asset(s) have deadlines computed against "
                "the current survival curve. Those dates move when the curve is "
                "re-fitted."
            ),
        })

    # Collapse duplicates, keeping the largest exposure per threat.
    merged: dict[str, dict] = {}
    for finding in findings:
        key = finding["threat"]
        if key not in merged or finding["exposed_count"] > merged[key]["exposed_count"]:
            merged[key] = finding

    applicable = []
    for key, finding in merged.items():
        threat = _BY_KEY[key]
        applicable.append({
            **finding,
            "title": threat.title,
            "status": threat.status,
            "mitigation": threat.mitigation,
        })

    applicable.sort(key=lambda f: (STATUS_ORDER.get(f["status"], 9), -f["exposed_count"]))

    return {
        "estate_size": len(assets),
        "already_post_quantum": len(migrated),
        "still_vulnerable": len(still_vulnerable),
        "applicable_threats": applicable,
        "register_size": len(THREATS),
        "note": (
            "These are the risks that remain, or begin, after a post-quantum "
            "migration. Completing a migration changes which of them apply; it "
            "does not empty this list."
        ),
    }
